language: node
sudo: required
services:
- docker
branches:
  only:
  - master
  - development
install:
  - cd kauri-ops
  - source env_setup.sh --config-file config/config-devgke.json
  - cd ..
script:
  - cd kauri-ops
  - source env_setup.sh --config-file config/config-devgke.json
