common_cache_key: &common_cache_key
  key: dependency-cache-{{ checksum "../ocaml-version" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "reason.opam" }}-{{ checksum "rebuild.opam" }}-{{ checksum "rtop.opam" }}

esy_cache_key: &esy_cache_key
  key: esy-cache-{{ checksum "esy.json" }}-{{ checksum "esy.lock" }}-{{ checksum ".circleci/config.yml" }}

esy_post_build_cache_key: &esy_post_build_cache_key
  key: esy-post-build-cache-{{ checksum "esy.json" }}-{{ checksum "esy.lock" }}-{{ checksum ".circleci/config.yml" }}

version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-9_ocaml-4.02.3
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.02.3"
      - NPM_CONFIG_PREFIX: "~/.npm-global"
    steps:
      - checkout
      - run:
          name: "Install npm"
          command: |
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            sudo apt-get install -y nodejs
            mkdir -p ~/.npm-global
            npm config set prefix $NPM_CONFIG_PREFIX
      - restore_cache:
          <<: *esy_cache_key
      - restore_cache:
          <<: *esy_post_build_cache_key
      - run:
          name: "Install esy"
          command: npm install -g esy@preview
      - run:
          name: 'esy install'
          command: |
            cd packages/kauri-web;
            yarn install
      - save_cache:
          <<: *esy_cache_key
          paths:
            - ~/.npm-global
            - ~/.esy
      - run:
          name: 'esy build'
          command: |
            ~/.npm-global/bin/esy build
            _build/install/default/bin/refmt --version
      # Use both pre and post build caches so that we're more likely
      # to have dependencies cached. `esy build` is more likely to fail,
      # so this will make the push that fixes the build faster
      - save_cache:
          <<: *esy_post_build_cache_key
          paths:
            - ~/.esy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  