common_cache_key: &common_cache_key
  key: dependency-cache-{{ checksum "../ocaml-version" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "reason.opam" }}-{{ checksum "rebuild.opam" }}-{{ checksum "rtop.opam" }}

esy_cache_key: &esy_cache_key
  key: esy-cache-{{ checksum "esy.json" }}-{{ checksum "esy.lock" }}-{{ checksum ".circleci/config.yml" }}

esy_post_build_cache_key: &esy_post_build_cache_key
  key: esy-post-build-cache-{{ checksum "esy.json" }}-{{ checksum "esy.lock" }}-{{ checksum ".circleci/config.yml" }}

common_steps: &common_steps
  steps:
    - run:
        name: "Install npm"
        command: |
          curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
          sudo apt-get install -y nodejs
          mkdir -p ~/.npm-global
          npm config set prefix $NPM_CONFIG_PREFIX
    - checkout
    - run:
        name: "Note OCAML_VERSION for cache"
        command: echo $OCAML_VERSION > ../ocaml-version
    - restore_cache:
        <<: *common_cache_key
    - run:
        name: "Initialize opam"
        command: |
          opam init --auto-setup --dot-profile=~/.bash_profile
          opam remote add ocamlorg https://opam.ocaml.org -p 0 || true
          opam remote remove default || true
    - run:
        name: "Install deps"
        command: |
          opam update
          opam install -y jbuilder
          opam install -y menhir.20170712
    - run:
        name: 'opam pin'
        command: |
          opam pin add -y reason .
          opam pin add -y rtop .
    - save_cache:
        <<: *common_cache_key
        paths:
          - ~/.opam
          - ~/.npm-global
    - run:
        name: 'Source env setup'
        command: |
          source ~/.bash_profile
          eval `opam config env`
          ls
          cd kauri-ops
          ls
          source env_setup.sh --config-file config/config-devgke.json
    - run:
        name: 'Check git is clean'
        command: git diff --exit-code

version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:debian-9_ocaml-4.02.3
    environment:
      - TERM: dumb
      - OCAML_VERSION: "4.02.3"
      - NPM_CONFIG_PREFIX: "~/.npm-global"
    <<: *common_steps
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  