apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: "frontend"
    kubernetes.io/tls-acme: "true"
  name: frontend-ingress
  namespace: dev2
spec:
  tls:
  - hosts:
    - dev2.kauri.io
    secretName: dev2-frontend-tls
  rules:
    - host: dev2.kauri.io
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
            path: /
